---
language: python
python: "2.7"
os: linux
dist: trusty

sudo: required

# Install ansible

before_install:
  - sudo apt-get install python-setuptools
  - sudo easy_install pip
  # Install ansible
  - sudo pip install -I "ansible"


install:

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test Demo case 1
  - ansible-playbook tests/test.yml -i tests/inventory
  # test login pages

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
