---
- name: Setup zones in Bind configuration
  template: 
    src: named.conf.local.j2 
    dest: "{{ bind_configs_dir }}/named.conf.local" 
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
    validate: "/usr/sbin/named-checkconf %s"
  notify: reload bind