---
- name: Installed Bind9 package
  apt:
    name: "{{ item }}"
    state: "{{ bind_pkg_state}}"
  with_items: "{{ bind_pkgs }}"

- name: Created the log directory for bind
  file:
    path: "{{ bind_log_dir }}"
    state: directory
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"

- name: Check ACL for the zones folder
  file:
    path: "{{ bind_zones_dir }}"
    state: directory
    owner: root
    group: "{{ bind_group }}"

- name: Setup default zones
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ bind_configs_dir }}/{{ item }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
    force: no
    validate: "/usr/sbin/named-checkzone {{ item }} %s"
  with_items:
    - db.0
    - db.127
    - db.255
    - db.empty
    - db.local
    - db.root
  when: bind_config_default_zones == 'yes'
  notify: reload bind