---
- include: setup_bind_conf.yml
  when: bind_pkg_state in ['present', 'installed', 'latest']
  tags: setup_bind_config

- include: create_master_zones.yml
  with_items: "{{ bind_config_master_zones }}"
  tags: setup_bind_master_zones

- name: Create slave zones files
  file: 
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0600
    path: "{{ bind_zones_dir }}/{{ bind_zones_slaves_dir }}/db.{{ item.name }}"
    state: touch
  with_items: "{{ bind_config_slave_zones }}"
  tags: setup_bind_slave_zones
  notify: reload bind

  #list files present in the masters folder
- shell: "ls -1 {{ bind_zones_dir }}/{{ bind_zones_masters_dir }}/"
  register: master_content
  when: master_zone_files
  
  #remove unmanaged files.
- name: Clean Master folder
  file:
    path: "{{ bind_zones_dir }}/{{ bind_zones_masters_dir }}/{{ item }}"
    state: absent
  with_items: "{{ master_content.stdout_lines }}"
  when: item not in master_zone_files

- include: setup_host_dns.yml
  when: host_dns_srv == 'self' 
  tags: setup_host_dns
