---
- include: setup_bind_conf.yml
  when: bind_pkg_state in ['present', 'installed', 'latest']
  tags: setup_bind_config

- include: create_master_zones.yml
  with_items: "{{ bind_config_master_zones }}"
  tags: setup_bind_master_zones

- name: Create slave zones files
  command: touch "{{ bind_zones_dir }}/{{ bind_zones_slaves_dir }}/db.{{ item.name }}"
  args:
    creates: "{{ bind_zones_dir }}/{{ bind_zones_slaves_dir }}/db.{{ item.name }}"
  with_items: "{{ bind_config_slave_zones }}"
  tags: setup_bind_slave_zones
  notify: reload bind

- include: setup_host_dns.yml
  when: host_dns_srv == 'self' 
  tags: setup_host_dns
