---
  # install requirements
- include: setup_bind_conf.yml
  when: bind_pkg_state in ['present', 'installed', 'latest']
  tags: setup_bind_config

  # generate and create masters zones files
- include: create_master_zones.yml
  with_items: "{{ bind_config_master_zones }}"
  tags: setup_bind_master_zones

  # create slave zones files
- include: create_slaves_zones.yml
  with_items: "{{ bind_config_slave_zones }}"
  tags: setup_bind_slave_zones

  #remove unmanaged zone files
- include: remove_unmanaged_files.yml
  when: remove_unmanaged_files

- include: setup_host_dns.yml
  when: host_dns_srv == 'self' 
  tags: setup_host_dns
