---
  # install requirements
- name: Make sure bind is installed and running
  include: install_bind.yml
  when: bind_pkg_state in ['present', 'installed', 'latest']
  tags: install_bind

  # configure named.conf.option
- name: configure named.conf.options
  include: configure_options.yml
  tags:  configure_options
  
  # configure named.conf.local
- name: configure named.conf.local
  include: configure_local.yml
  tags:  configure_local

  # generate and create masters zones files
- include: create_master_zones.yml
  with_items: "{{ bind_config_master_zones }}"
  tags: setup_bind_master_zones

  # create slave zones files
- name: works on slave zones files
  include: create_slaves_zones.yml
  with_items: "{{ bind_config_slave_zones }}"
  tags: setup_bind_slave_zones

  #remove unmanaged zone files
- name: Clean the zone files folder
  include: remove_unmanaged_files.yml
  when: remove_unmanaged_files

- include: setup_host_dns.yml
  when: host_dns_srv == 'self' 
  tags: setup_host_dns
