---
#list files present in the zone files folder
- name: "Discover files in {{ bind_zones_dir }}"
  find:
    paths: "{{ bind_zones_dir }}"
  register: folder_content

#remove unmanaged files.
- name: Clean the zone files folder
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ folder_content.files }}"
  when: item.path.split('/')[-1] not in list_zone_files
