---
#list files present in the zone files folder
- shell: "ls -1 {{ bind_zones_dir }}/"
  register: folder_content
#remove unmanaged files.
- name: Clean the zone files folder
  file:
    path: "{{ bind_zones_dir }}/{{ item }}"
    state: absent
  with_items: "{{ folder_content.stdout_lines }}"
  when: item not in list_zone_files
