---
- name: Installed Bind9 package
  apt:
    name: "{{ item }}"
    state: "{{ bind_pkg_state}}"
  with_items: "{{ bind_pkgs }}"

- name: Created the log directory for bind
  file:
    path: "{{ bind_log_dir }}"
    state: directory
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"

- name: Check ACL for the zones folder
  file:
    path: "{{ bind_zones_dir }}"
    state: directory
    owner: root
    group: "{{ bind_group }}"

- name: Load default options
  include_vars: defaults/default_options.yml

- name: Load options file
  include_vars: "{{ options_file }}"
  when: options_file is defined

- name: Generate Bind options
  template: 
    src: clauses/options.j2
    dest: "{{ bind_configs_dir }}/named.conf.options" 
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
    validate: "/usr/sbin/named-checkconf %s"
  notify: reload bind

- name: Setup default zones
  copy:
    src: "./files/{{ item }}"
    dest: "{{ bind_configs_dir }}/{{ item }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
    force: no
    validate: "/usr/sbin/named-checkzone {{ item }} %s"
  with_items:
    - db.0
    - db.127
    - db.255
    - db.empty
    - db.local
    - db.root
  when: bind_config_default_zones == 'yes'
  notify: reload bind

- name: Setup zones in Bind configuration
  template: 
    src: named.conf.local.j2 
    dest: "{{ bind_configs_dir }}/named.conf.local" 
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
    mode: 0644
    validate: "/usr/sbin/named-checkconf %s"
  notify: reload bind
